name: Test

on:
  push:
    branches:
      - "*"
  pull_request:


jobs:
  component-testing:
    name: Test modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: install k8s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -s - --docker
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

      - name: deploy infrastructure
        run: helm install --values ./deployment/helm/infrastructure/values.yaml infrastructure ./deployment/helm/infrastructure
      - name: build cdl images
        run: DOCKER_BUILDKIT=1 ENV=DEV ./build.sh
      - name: add kafka topics
        run: |
          topics=(cdl.data.input CDL_SCHEMA_SYNCHRO cdl.document.data cdl.timeseries.data cdl.timeseries.generic-druid cdl.timeseries2.data)
          for topic in "${topics[@]}"
          do
          kubectl exec infrastructure-kafka-0 /bin/bash -- /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic $topic --bootstrap-server localhost:9092
          done
      - name: deploy cdl
        run: helm install --values ./deployment/helm/cdl/values-local.yaml cdl ./deployment/helm/cdl
      - name: wait
        run: sleep 20
      - name: get status
        run: kubectl get pods
